#ifndef EventH
#define EventH
enum Event {
	EVENT_X, EVENT_Y, RESTART, SELF_TEST_FAILED, SELF_TEST_OK,
	INITIALIZED, CONFIGURE, CONFIGURATION_ENDED, STOP, SUSPEND, RESUME, START_RUN, CH_MODE
};
#endif
